---
title: "On the origin of citations"
author: "Caitlin Anderson"
date: "September 15, 2015"
output:
  word_document: default
  html_document:
    fig_caption: yes
    fig_height: 8
    fig_width: 8
    highlight: espresso
    number_sections: yes
    theme: cerulean
    toc: yes
---

#Load the data

```{r load data}
counts_raw <- read.delim("data/counts-raw.txt.gz")
counts_norm <- read.delim("data/counts-norm.txt.gz")
```

#Data exploration

What's the distribution of authors in all articles of our data set?

```{r author histogram, echo=FALSE, fig.cap="**Figure 1. Number of Authors per Article**"}
hist(counts_raw$authorsCount, main="Authors per paper", xlab="# authors")
```

How popular are articles on Facebook?
```{r facebook shares histogram, echo=FALSE, fig.cap="**Figure 2. Number of Facebook Shares per Article**"}
hist(counts_raw$facebookShareCount, main="Facebook Shares per Article", xlab= "# Shares", xlim=c(0,1000))
```
  
The average number of Facebook shares per paper in the data set is `r mean(counts_raw$facebookShareCount)`.

